#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS
# Path to the passwd file
FILE="/etc/passwd"

# Check if the file exists
if [ -e "$FILE" ]; then
    # Use while loop to read lines from the file
    while IFS=: read -r username password userid groupid user_info homedir shell; do
        # Display formatted output
        echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
        echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_info"
        echo "-----------------------------------"
    done < "$FILE"
else
    echo "Error: $FILE does not exist."
fi
