#!/usr/bin/env bash
# Bash script to display "Best School" 10 times
# On the 9th iteration, display "Best School" and then "Hi" on a new line

counter=0

while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done
