#!/usr/bin/env bash
#Loops from 1 to 20 and displays:
#  "bad luck from China" for the 4th loop iteration
#  "bad luck from Japan" for the 9th loop iteration
#  "bad luck from Italy" for the 17th loop iteration

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter and then bad luck from China"
            ;;
        9)
            echo "$counter and then bad luck from Japan"
            ;;
        17)
            echo "$counter and then bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    ((counter++))
done
