#!/usr/bin/env bash
#Loops from 1 to 10 and displays:
#  "bad luck from China" for the 4th loop iteration
#  "bad luck from Japan" for the 9th loop iteration
#  "bad luck from Italy" for the 17th loop iteration

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((counter++))
done
