#!/usr/bin/env bash
# Bash script to display numbers from 1 to 20
# Display different messages based on the loop iteration

counter=1

while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter and then bad luck from China"
            ;;
        9)
            echo "$counter and then bad luck from Japan"
            ;;
        17)
            echo "$counter and then bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    ((counter++))
done
