#!/usr/bin/env bash
# Bash script to display content of the current directory in a list format
# Show only the part of the name after the first dash

for file in *; do
    # Check if the file is not a hidden file
    if [[ $file != .* ]]; then
        # Extract the part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name_after_dash"
    fi
done
